export const PRODUCTS_IS_LOADING = 'PRODUCTS_IS_LOADING';
export const PRODUCTS_DATA_FETCHED = 'PRODUCTS_DATA_FETCHED';
export const PRODUCTS_DATA_ERROR = 'PRODUCTS_DATA_ERROR';

export const VENDORS_IS_LOADING = 'VENDORS_IS_LOADING';
export const VENDORS_DATA_FETCHED = 'VENDORS_DATA_FETCHED';
export const VENDORS_DATA_ERROR = 'VENDORS_DATA_ERROR';

export const PROMOTION_IS_LOADING  = 'PROMOTION_IS_LOADING';
export const PROMOTION_DATA_FETCHED  = 'PROMOTION_DATA_FETCHED';
export const PROMOTION_DATA_ERROR = 'PROMOTION_DATA_ERROR';